apiVersion: batch/v1
kind: Job
metadata:
  name: botium-box-init
spec:
  template:
    metadata:
      name: botium-box-init
    spec:
      containers:
        - name: botium-box-init
          image: alpine
          command: ["/bin/sh"]
          args:
            - -c
            - apk add curl unzip && mkdir -p /app/storage/testsets && mkdir -p /app/storage/resources && mkdir -p /app/storage/botiumwork && cd /tmp && curl -L https://github.com/codeforequity-at/botium-box-premium-dist/archive/master.zip -o master.zip && unzip master.zip && cp botium-box-premium-dist-master/resources/* /app/storage/resources && ls -a /app/storage/resources 
          volumeMounts:
          - mountPath: "/app/storage"
            name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: botium-box-storage
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: botium-box-prisma-init
spec:
  template:
    metadata:
      name: botium-box-prisma-init
    spec:
      containers:
        - name: botium-box-prisma-init
          image: botium/botium-box-server:{{ .Values.BOTIUM_BOX_VERSION }}
          command: ["/bin/sh"]
          args: ["-c", "npm run prisma-deploy && npm run prisma-seed"]          
          env:
            - name: DEBUG
              value: botium*
            - name: PRISMA_MANAGEMENT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: PRISMA_MANAGEMENT_API_SECRET
            - name: PRISMA_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: PRISMA_ENDPOINT
            - name: PRISMA_SECRET
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: PRISMA_SECRET
            - name: PRISMA_CLOUD_SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: PRISMA_CLOUD_SESSION_KEY
            - name: SEED_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: SEED_PASSWORD
      restartPolicy: Never
  backoffLimit: 0