apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: botium-box-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - botiumbox.com
    secretName: botium-box-certs
  rules:
  - host: {{ .Values.FQDN }}
    http:
      paths:
      - path: /
        backend:
          serviceName: botium-box
          servicePort: 4000
