apiVersion: v1
kind: Secret
metadata:
  name: botium-box-secrets
  labels:
    name: secrets
    app: botium-box
stringData:
  LICENSE_KEY: "{{ .Values.LICENSE_KEY }}"
  PRISMA_MANAGEMENT_API_SECRET: "{{ .Values.PRISMA_MANAGEMENT_API_SECRET }}"
  PRISMA_SECRET: "{{ .Values.PRISMA_SECRET }}"
  SEED_ADMIN_EMAIL: "{{ .Values.SEED_ADMIN_EMAIL }}"
  SEED_PASSWORD: "{{ .Values.SEED_PASSWORD }}"
  BOTIUMBOX_QUEUE_REDISURL: "redis://:{{ .Values.REDIS_PASSWORD }}@{{ .Values.REDIS_SERVICE }}:6379/{{ .Values.REDIS_SELECT_INDEX }}"
  SMTP_USER: "{{ .Values.SMTP_USER }}"
  SMTP_PASSWORD: "{{ .Values.SMTP_PASSWORD }}"
  COACH_WORKER_APIKEY: "{{ .Values.COACH_WORKER_APIKEY }}"
  SPEECH_PROCESSING_APIKEY: "{{ .Values.SPEECH_PROCESSING_APIKEY }}"    
  GOOGLE_TRANSLATE_CLIENT_EMAIL: "{{ .Values.GOOGLE_TRANSLATE_CLIENT_EMAIL }}"
  GOOGLE_TRANSLATE_PRIVATE_KEY: "{{ .Values.GOOGLE_TRANSLATE_PRIVATE_KEY }}"
  BOTIUMBOX_SENTRY_DSN: "{{ .Values.BOTIUMBOX_SENTRY_DSN }}"
  {{- if .Values.INSTALL_PRISMA }}
  MYSQL_ROOT_PASSWORD: "{{ .Values.MYSQL_ROOT_PASSWORD }}"
  PRISMA_CONFIG: |
    port: 4466
    databases:
      default:
        connector: mysql
        host: {{ .Values.MYSQL_HOST }}
        port: 3306
        user: root
        password: "{{ .Values.MYSQL_ROOT_PASSWORD }}"
        migrations: true
  {{- end }}
type: Opaque
