{{- if .Values.INSTALL_PRISMA }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage
  labels:
    name: mysql-storage
    app: botium-box
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.STORAGE_CLASS_MYSQL }}
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    name: mysql
    app: botium-box
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mysql
        app: botium-box
        tier: backend
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - name: mysql-3306
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
              subPath: mysql-data
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-storage
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  app: botium-box
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    name: mysql
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prisma
  labels:
    name: prisma
    app: botium-box
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: prisma
        app: botium-box
        tier: backend
    spec:
      containers:
        - name: prisma
          {{- if eq .Values.CONTAINER_REGISTRY "" }}
          image: botium/prisma:{{ .Values.BOTIUM_BOX_VERSION }}
          {{- else }}
          image: {{ .Values.CONTAINER_REGISTRY }}/botium/prisma:{{ .Values.BOTIUM_BOX_VERSION }}
          {{- end }}
          ports:
            - name: prisma-4466
              containerPort: 4466
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: PRISMA_CONFIG
---
apiVersion: v1
kind: Service
metadata:
  name: prisma
  app: botium-box
spec:
  ports:
    - port: 4466
      targetPort: 4466
      protocol: TCP
  selector:
    name: prisma
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-admin
  labels:
    name: mysql-admin
    app: botium-box
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: mysql-admin
        app: botium-box
        tier: backend
    spec:
      containers:
        - name: mysql-admin
          image: adminer
          ports:
            - name: admin-8080
              containerPort: 8080
          env:
            - name: ADMINER_DEFAULT_SERVER
              value: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-admin
  app: botium-box
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: mysql-admin
{{- end }}
