apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botium-box-storage
  labels:
    name: botium-box-storage
    app: botium-box
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.STORAGE_CLASS_BOX }}
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: box-server
  labels:
    name: box-server
    app: botium-box
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: box-server
        app: botium-box
        tier: frontend
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: box-server
          {{- if eq .Values.CONTAINER_REGISTRY "" }}
          image: botium/botium-box-server:{{ .Values.BOTIUM_BOX_VERSION }}
          {{- else }}
          image: {{ .Values.CONTAINER_REGISTRY }}/botium/botium-box-server:{{ .Values.BOTIUM_BOX_VERSION }}
          {{- end }}
          imagePullPolicy: Always
          {{- if eq .Values.INSTALL_PRISMA false }}
          command: ["/bin/sh"]
          args: ["-c", "npm run prisma-deploy && npm run prisma-seed && node -r dotenv-flow/config dist/botium-box-server.js"]
          {{- end }}
          ports:
            - name: box-4000
              containerPort: 4000
          volumeMounts:
          - mountPath: "/app/server/storage/"
            name: botium-box-storage
          env:
            - name: DEBUG
              value: botium*
            - name: TESTSETDIR
              value: /app/server/storage/testsets
            - name: RESOURCESDIR
              value: /app/server/storage/resources
            - name: TEMPDIR
              value: /app/server/storage/botiumwork
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: LICENSE_KEY
            - name: PRISMA_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: PRISMA_ENDPOINT
            - name: PRISMA_SECRET
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: PRISMA_SECRET
            - name: PRISMA_MANAGEMENT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: PRISMA_MANAGEMENT_API_SECRET
            - name: SEED_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: SEED_ADMIN_EMAIL
            - name: SEED_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: SEED_PASSWORD
            - name: BOTIUMBOX_QUEUE_REDISURL
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: BOTIUMBOX_QUEUE_REDISURL
            - name: BOTIUMBOX_QUEUE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_QUEUE_PREFIX
            - name: BOTIUMBOX_AGENT_COUNT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_AGENT_COUNT
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: SMTP_PORT
            {{- if .Values.SMTP_SECURE }}
            - name: SMTP_SECURE
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: SMTP_SECURE
            {{- end }}
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: SMTP_PASSWORD
            {{- if .Values.ACTIVATE_ZAP }}
            - name: ZAP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: ZAP_ENDPOINT
            {{- end }}
            - name: COACH_WORKER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: COACH_WORKER_ENDPOINT
            - name: COACH_WORKER_APIKEY
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: COACH_WORKER_APIKEY
            - name: JWT_EXPIRY_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: JWT_EXPIRY_MINUTES
      volumes:
        - name: botium-box-storage
          persistentVolumeClaim:
            claimName: botium-box-storage
---
apiVersion: v1
kind: Service
metadata:
  name: box-server
spec:
  ports:
    - port: 4000
  selector:
    name: box-server
    app: botium-box
{{- if .Values.INSTALL_INGRESS }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: box-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    rancher.io/globalDNS.hostname: {{ .Values.SHORTNAME }}.botiumbox.com
    cert-manager.io/cluster-issuer: {{ .Values.SHORTNAME }}-letsencrypt-prod
    nginx.ingress.kubernetes.io/server-snippet: |
      ssl_stapling on;
      ssl_stapling_verify on;
spec:
  tls:
  - hosts:
    - {{ .Values.SHORTNAME }}.botiumbox.com
    secretName: {{ .Values.SHORTNAME }}.botiumbox-com-tls
  rules:
  - host: {{ .Values.SHORTNAME }}.botiumbox.com
    http:
      paths:
      - path: /
        backend:
          serviceName: box-server
          servicePort: 4000
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ .Values.SHORTNAME }}-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: florian.treml@botium.at
    privateKeySecretRef:
      name: {{ .Values.SHORTNAME }}-letsencrypt-prod
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.SHORTNAME }}.botiumbox-com
spec:
  secretName: {{ .Values.SHORTNAME }}.botiumbox-com-tls
  issuerRef:
    name: {{ .Values.SHORTNAME }}-letsencrypt-prod
  commonName: {{ .Values.SHORTNAME }}.botiumbox.com
  dnsNames:
  - {{ .Values.SHORTNAME }}.botiumbox.com
{{- end }}
