apiVersion: v1
kind: Secret
metadata:
  name: botium-box-secrets
  labels:
    name: secrets
    app: botium-box
stringData:
  LICENSE_KEY: "{{ .Values.LICENSE_KEY }}"
  PRISMA_MANAGEMENT_API_SECRET: "{{ .Values.PRISMA_MANAGEMENT_API_SECRET }}"
  SEED_ADMIN_EMAIL: "{{ .Values.SEED_ADMIN_EMAIL }}"
  SEED_PASSWORD: "{{ .Values.SEED_PASSWORD }}"
  BOTIUMBOX_QUEUE_REDISURL: "redis://:{{ .Values.REDIS_PASSWORD }}@redis:6379"
  SMTP_USER: "{{ .Values.SMTP_USER }}"
  SMTP_PASSWORD: "{{ .Values.SMTP_PASSWORD }}"
type: Opaque
