apiVersion: v1
kind: Secret
metadata:
  name: botium-box-secrets
  labels:
    name: secrets
    app: botium-box
stringData:
  LICENSE_KEY: "{{ .Values.LICENSE_KEY }}"
  PRISMA_MANAGEMENT_API_SECRET: "{{ .Values.PRISMA_MANAGEMENT_API_SECRET }}"
  SMTP_USER: "{{ .Values.SMTP_USER }}"
  SMTP_PASSWORD: "{{ .Values.SMTP_PASSWORD }}"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: botium-box-acme-route53
stringData:
  AWS_ACCESS_KEY_ID: "{{ .Values.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.AWS_SECRET_ACCESS_KEY }}"
type: Opaque
