apiVersion: v1
kind: ConfigMap
metadata:
  name: botium-box-configmap
  labels:
    name: config
    app: botium-box
data:
  LICENSE_KEY: "{{ .Values.LICENSE_KEY }}"
  COACH_WORKER_ENDPOINT: "{{ .Values.COACH_WORKER_ENDPOINT }}"
  PRISMA_CONFIG_FILE: /app/prisma-config/prisma-config.json
  ZAP_ENDPOINT: http://zap:8080
  SMTP_HOST: "{{ .Values.SMTP_HOST }}"
  SMTP_PORT: "{{ .Values.SMTP_PORT }}"
  BOTIUMBOX_AGENT_LIST: "{{ .Values.BOTIUMBOX_AGENT_LIST }}"
  BOTIUMBOX_QUEUE_PREFIX: "{{ .Values.BOTIUMBOX_QUEUE_PREFIX }}"
