apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botium-box-mini-storage
  labels:
    name: botium-box-mini-storage
    app: botium-box
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.STORAGE_CLASS_BOX }}
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botium-box-mini-prisma-config-storage
  labels:
    name: botium-box-mini-prisma-config-storage
    app: botium-box
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.STORAGE_CLASS_BOX }}
  resources:
    requests:
      storage: 20Gi
