apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: box-server
  labels:
    name: box-server
    app: botium-box
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: box-server
        app: botium-box
        tier: frontend
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: box-server
          image: botium/botium-box-server:{{ .Values.BOTIUM_BOX_VERSION }}
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "node -r dotenv-flow/config dist/botium-box-server.js"]
          ports:
            - name: box-4000
              containerPort: 4000
          volumeMounts:
          - mountPath: "/app/storage/"
            name: botium-box-mini-storage
          - mountPath: "/app/prisma-config/"
            name: botium-box-mini-prisma-config-storage
          env:
            - name: DEBUG
              value: botium*
            - name: TESTSETDIR
              value: /app/server/testsets
            - name: TESTSETDIR_PUBLIC
              value: /app/server/testsets
            - name: TEMPDIR
              value: /app/server/botiumwork
            - name: BOTIUMBOX_SCANFORTESTSETS
              value: /app/datasets-mini
            - name: BOTIUMBOX_AGENT_LIST
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_AGENT_LIST
            - name: BOTIUMBOX_FEATURE_FILEBROWSER
              value: "0"
            - name: BOTIUMBOX_FEATURE_DELETETESTSESSION
              value: "0"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: JWT_SECRET
            - name: PRISMA_CONFIG_FILE
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: PRISMA_CONFIG_FILE
            - name: LICENSE_KEY
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: LICENSE_KEY
            - name: BOTIUMBOX_QUEUE_REDISURL
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_QUEUE_REDISURL
            - name: COACH_WORKER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: COACH_WORKER_ENDPOINT
            - name: COACH_WORKER_APIKEY
              valueFrom:
                secretgMapKeyRef:
                  name: botium-box-secrets
                  key: COACH_WORKER_APIKEY
            - name: PRISMA_MANAGEMENT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: PRISMA_MANAGEMENT_API_SECRET
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: SMTP_PORT
            {{- if .Values.SMTP_SECURE }}
            - name: SMTP_SECURE
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: SMTP_SECURE
            {{- end }}
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: SMTP_PASSWORD
            {{- if .Values.INSTALL_ZAP }}
            - name: ZAP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: ZAP_ENDPOINT
            {{- end }}
      volumes:
        - name: botium-box-mini-storage
          persistentVolumeClaim:
            claimName: botium-box-mini-storage
        - name: botium-box-mini-prisma-config-storage
          persistentVolumeClaim:
            claimName: botium-box-mini-prisma-config-storage
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: box-server-shell
  labels:
    name: box-server-shell
    app: botium-box-shell
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: box-server-shell
        app: botium-box-shell
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
        - name: box-server
          image: botium/botium-box-server:{{ .Values.BOTIUM_BOX_VERSION }}
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "apk add curl-dev g++ make python dos2unix && git clone https://{{ .Values.BITBUCKET_USERNAME }}:{{ .Values.BITBUCKET_PASSWORD }}@bitbucket.org/botiumcoreteam/botium-box.git && cd botium-box && git fetch && git checkout feature/box-mini && npm install && npm run install:all && cd /app/server && while :; do echo 'Press <CTRL+C> to exit.'; sleep 1; done"]
          ports:
            - name: box-4000
              containerPort: 4000
          volumeMounts:
          - mountPath: "/app/storage/"
            name: botium-box-mini-storage
          - mountPath: "/app/prisma-config/"
            name: botium-box-mini-prisma-config-storage
          env:
            - name: DEBUG
              value: botium*
            - name: TESTSETDIR
              value: /app/server/testsets
            - name: TESTSETDIR_PUBLIC
              value: /app/server/testsets
            - name: TEMPDIR
              value: /app/server/botiumwork
            - name: BOTIUMBOX_SCANFORTESTSETS
              value: /app/datasets-mini
            - name: BOTIUMBOX_AGENT_LIST
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_AGENT_LIST
            - name: BOTIUMBOX_FEATURE_FILEBROWSER
              value: "0"
            - name: BOTIUMBOX_FEATURE_DELETETESTSESSION
              value: "0"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: JWT_SECRET
            - name: PRISMA_CONFIG_FILE
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: PRISMA_CONFIG_FILE
            - name: LICENSE_KEY
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: LICENSE_KEY
            - name: BOTIUMBOX_QUEUE_REDISURL
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_QUEUE_REDISURL
            - name: COACH_WORKER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: COACH_WORKER_ENDPOINT
            - name: PRISMA_MANAGEMENT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: PRISMA_MANAGEMENT_API_SECRET
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: SMTP_PORT
            {{- if .Values.SMTP_SECURE }}
            - name: SMTP_SECURE
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: SMTP_SECURE
            {{- end }}
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: SMTP_PASSWORD
            {{- if .Values.INSTALL_ZAP }}
            - name: ZAP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: ZAP_ENDPOINT
            {{- end }}
      volumes:
        - name: botium-box-mini-storage
          persistentVolumeClaim:
            claimName: botium-box-mini-storage
        - name: botium-box-mini-prisma-config-storage
          persistentVolumeClaim:
            claimName: botium-box-mini-prisma-config-storage
---
apiVersion: v1
kind: Service
metadata:
  name: box-server
spec:
  ports:
    - port: 4000
  selector:
    name: box-server
    app: botium-box
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: box-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.SHORTNAME }}-letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.SHORTNAME }}.botiumbox.com
    - '*.{{ .Values.SHORTNAME }}.botiumbox.com'
    secretName: {{ .Values.SHORTNAME }}.botiumbox-com-tls
  rules:
  - host: '*.{{ .Values.SHORTNAME }}.botiumbox.com'
    http:
      paths:
      - path: /
        backend:
          serviceName: box-server
          servicePort: 4000
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.SHORTNAME }}-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: florian.treml@botium.at
    privateKeySecretRef:
      name: {{ .Values.SHORTNAME }}-letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - '*.{{ .Values.SHORTNAME }}.botiumbox.com'
      dns01:
        route53:
          region: eu-west-1
          accessKeyID: "{{ .Values.AWS_ACCESS_KEY_ID }}"
          secretAccessKeySecretRef:
            name: botium-box-secrets
            key: AWS_SECRET_ACCESS_KEY
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.SHORTNAME }}.botiumbox-com
spec:
  secretName: {{ .Values.SHORTNAME }}.botiumbox-com-tls
  issuerRef:
    name: {{ .Values.SHORTNAME }}-letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - '*.{{ .Values.SHORTNAME }}.botiumbox.com'
  acme:
    config:
      - dns01:
          provider: route53
        domains:
          - '*.{{ .Values.SHORTNAME }}.botiumbox.com'
