apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: box-server
  labels:
    name: box-server
    app: botium-box
    tier: frontend
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: box-server
        app: botium-box
        tier: frontend
    spec:
      initContainers:
        - name: box-server-chmod-er-storage
          image: busybox:latest
          command:
          - /bin/chown
          - -R
          - "1000:1000"
          - /app/server/storage
          volumeMounts:
          - mountPath: "/app/server/storage"
            name: botium-box-mini-storage
        - name: box-server-chmod-er-config
          image: busybox:latest
          command:
          - /bin/chown
          - -R
          - "1000:1000"
          - /app/prisma-config/
          volumeMounts:
          - mountPath: "/app/prisma-config/"
            name: botium-box-mini-prisma-config-storage
      containers:
        - name: box-server
          imagePullPolicy: Always
          {{- if eq .Values.CONTAINER_REGISTRY "" }}
          image: botium/botium-box-server:{{ .Values.BOTIUM_BOX_VERSION }}
          {{- else }}
          image: {{ .Values.CONTAINER_REGISTRY }}/botium/botium-box-server:{{ .Values.BOTIUM_BOX_VERSION }}
          {{- end }}
          command: ["/bin/sh"]
          args: ["-c", "node -r dotenv-flow/config dist/botium-box-server.js"]
          ports:
            - name: box-4000
              containerPort: 4000
          volumeMounts:
          - mountPath: "/app/server/storage/"
            name: botium-box-mini-storage
          - mountPath: "/app/prisma-config/"
            name: botium-box-mini-prisma-config-storage
          env:
            - name: DEBUG
              value: botium*
            - name: RESOURCESDIR
              value: /app/server/storage/resources
            - name: TESTSETDIR
              value: /app/server/storage/testsets
            - name: BOTIUMBOX_SCANFORTESTSETS
              value: ""
            - name: BOTIUM_TEMPDIR
              value: /app/server/storage/botiumwork
            - name: NODE_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: NODE_OPTIONS
            - name: BOTIUMBOX_AGENT_LIST
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_AGENT_LIST
            - name: CHOKIDAR_USEPOLLING
              value: "1"
            - name: BOTIUMBOX_FEATURE_FILEBROWSER
              value: "1"
            - name: BOTIUMBOX_FEATURE_DELETETESTSESSION
              value: "0"
            - name: BOTIUMBOX_FEATURE_REPAIRTESTPROJECTHISTORY
              value: "0"
            - name: BOTIUMBOX_MAX_EXECUTION_INTERVAL_MINUTES
              value: "10"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: JWT_SECRET
            - name: PRISMA_CONFIG_FILE
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: PRISMA_CONFIG_FILE
            - name: BOTIUMBOX_AUDIT_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_AUDIT_FOLDER
            - name: LICENSE_KEY
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: LICENSE_KEY
            - name: BOTIUMBOX_QUEUE_REDISURL
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: BOTIUMBOX_QUEUE_REDISURL
            - name: BOTIUMBOX_QUEUE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_QUEUE_PREFIX
            - name: COACH_WORKER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: COACH_WORKER_ENDPOINT
            - name: COACH_WORKER_APIKEY
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: COACH_WORKER_APIKEY
            - name: PRISMA_MANAGEMENT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: PRISMA_MANAGEMENT_API_SECRET
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: SMTP_PORT
            {{- if .Values.SMTP_SECURE }}
            - name: SMTP_SECURE
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: SMTP_SECURE
            {{- end }}
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: SMTP_PASSWORD
            - name: BOTIUMBOX_CLEANUP_JOB_INTERVAL_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_CLEANUP_JOB_INTERVAL_MINUTES
            - name: BOTIUMBOX_KEEP_SUCCESS_SCREENSHOTS_DAYS
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_KEEP_SUCCESS_SCREENSHOTS_DAYS
            - name: BOTIUMBOX_KEEP_SUCCESS_CONVERSATION_DAYS
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_KEEP_SUCCESS_CONVERSATION_DAYS
            - name: BOTIUMBOX_KEEP_FAILED_SCREENSHOTS_DAYS
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_KEEP_FAILED_SCREENSHOTS_DAYS
            - name: BOTIUMBOX_KEEP_FAILED_CONVERSATION_DAYS
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_KEEP_FAILED_CONVERSATION_DAYS
            - name: BOTIUMBOX_KEEP_COACH_DETAILS_DAYS
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_KEEP_COACH_DETAILS_DAYS
            {{- if .Values.ACTIVATE_ZAP }}
            - name: ZAP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: ZAP_ENDPOINT
            {{- end }}
            - name: BOTIUMBOX_SMARTLOOK_KEY
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: BOTIUMBOX_SMARTLOOK_KEY
            - name: BOTIUMBOX_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: BOTIUMBOX_SENTRY_DSN                
            - name: BOTIUMBOX_PASSPORT_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: BOTIUMBOX_PASSPORT_ADMINPASSWORD
            - name: GOOGLE_TRANSLATE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: GOOGLE_TRANSLATE_CLIENT_EMAIL
            - name: GOOGLE_TRANSLATE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: GOOGLE_TRANSLATE_PRIVATE_KEY
            - name: PARAPHRASING_APIKEY
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: PARAPHRASING_APIKEY
      volumes:
        - name: botium-box-mini-storage
          persistentVolumeClaim:
            claimName: botium-box-mini-storage
        - name: botium-box-mini-prisma-config-storage
          persistentVolumeClaim:
            claimName: botium-box-mini-prisma-config-storage
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: box-server-shell
  labels:
    name: box-server-shell
    app: botium-box-shell
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: box-server-shell
        app: botium-box-shell
    spec:
      containers:
        - name: box-server
          {{- if eq .Values.CONTAINER_REGISTRY "" }}
          image: botium/botium-box-server:{{ .Values.BOTIUM_BOX_VERSION }}
          {{- else }}
          image: {{ .Values.CONTAINER_REGISTRY }}/botium/botium-box-server:{{ .Values.BOTIUM_BOX_VERSION }}
          {{- end }}
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "git clone https://{{ .Values.BITBUCKET_USERNAME }}:{{ .Values.BITBUCKET_PASSWORD }}@bitbucket.org/botiumcoreteam/botium-datasets.git && mkdir -p /app/datasets-mini && cp -R botium-datasets/mini/* /app/datasets-mini && git clone https://{{ .Values.BITBUCKET_USERNAME }}:{{ .Values.BITBUCKET_PASSWORD }}@bitbucket.org/botiumcoreteam/botium-box.git && cd botium-box && git fetch && git checkout {{ if eq .Values.BOTIUM_BOX_VERSION "develop" }}develop{{ else }} release/{{ .Values.BOTIUM_BOX_VERSION }}{{ end }} && mkdir packages/botium-box-server/node_modules && ln -s ../../license-creator packages/botium-box-server/node_modules/license-creator && ln -s ../../botium-box-shared packages/botium-box-server/node_modules/botium-box-shared && cd /app/server && while :; do echo 'Press <CTRL+C> to exit.'; sleep 10; done"]
          ports:
            - name: box-4000
              containerPort: 4000
          volumeMounts:
          - mountPath: "/app/storage/"
            name: botium-box-mini-storage
          - mountPath: "/app/prisma-config/"
            name: botium-box-mini-prisma-config-storage
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
          env:
            - name: DEBUG
              value: botium*
            - name: NODE_PATH
              value: /app/server/node_modules
            - name: RESOURCESDIR
              value: /app/storage/resources
            - name: BOTIUMBOX_SCANFORTESTSETS
              value: /app/datasets-mini
            - name: PRISMA_BIN_FILE
              value: /app/server/node_modules/.bin/prisma
            - name: PRISMA_CONFIG_FILE
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: PRISMA_CONFIG_FILE
            - name: LICENSE_KEY
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: LICENSE_KEY
            - name: PRISMA_MANAGEMENT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: PRISMA_MANAGEMENT_API_SECRET
            - name: BOTIUMBOX_QUEUE_REDISURL
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: BOTIUMBOX_QUEUE_REDISURL
            - name: BOTIUMBOX_QUEUE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_QUEUE_PREFIX
      volumes:
        - name: botium-box-mini-storage
          persistentVolumeClaim:
            claimName: botium-box-mini-storage
        - name: botium-box-mini-prisma-config-storage
          persistentVolumeClaim:
            claimName: botium-box-mini-prisma-config-storage
---
apiVersion: v1
kind: Service
metadata:
  name: box-server
spec:
  ports:
    {{- if eq .Values.MAINTENANCE false }}
    - port: 4000
    {{- else }}
    - port: 4000
      targetPort: 80
      protocol: TCP
    {{- end }}
  selector:
    {{- if eq .Values.MAINTENANCE false }}
    name: box-server
    app: botium-box
    {{- else }}
    app: maintenance
    {{- end }}
{{- if .Values.MAINTENANCE }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maintenance
  labels:
    app: maintenance
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: maintenance
        tier: backend
    spec:
      containers:
        - name: maintenance
          image: adrianrudnik/maintenance-server:latest
          ports:
            - name: mt-80
              containerPort: 80
{{- end }}
{{- if .Values.INSTALL_INGRESS }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: box-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.SHORTNAME }}-letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.SHORTNAME }}.botiumbox.com
    - '*.{{ .Values.SHORTNAME }}.botiumbox.com'
    secretName: {{ .Values.SHORTNAME }}.botiumbox-com-tls
  rules:
  - host: '*.{{ .Values.SHORTNAME }}.botiumbox.com'
    http:
      paths:
      - path: /
        backend:
          serviceName: box-server
          servicePort: 4000
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.SHORTNAME }}-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: florian.treml@botium.at
    privateKeySecretRef:
      name: {{ .Values.SHORTNAME }}-letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - '*.{{ .Values.SHORTNAME }}.botiumbox.com'
      dns01:
        route53:
          region: eu-west-1
          accessKeyID: "{{ .Values.AWS_ACCESS_KEY_ID }}"
          secretAccessKeySecretRef:
            name: botium-box-secrets
            key: AWS_SECRET_ACCESS_KEY
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.SHORTNAME }}.botiumbox-com
spec:
  secretName: {{ .Values.SHORTNAME }}.botiumbox-com-tls
  issuerRef:
    name: {{ .Values.SHORTNAME }}-letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - '*.{{ .Values.SHORTNAME }}.botiumbox.com'
  acme:
    config:
      - dns01:
          provider: route53
        domains:
          - '*.{{ .Values.SHORTNAME }}.botiumbox.com'
{{- end }}
