apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botium-box-storage
  labels:
    name: botium-box-storage
    app: botium-box
    tier: frontend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.STORAGE_CLASS_BOX }}
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage
  labels:
    name: mysql-storage
    app: botium-box
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.STORAGE_CLASS_MYSQL }}
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-storage
  labels:
    name: backup-storage
    app: botium-box
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.STORAGE_CLASS_BACKUP }}
  resources:
    requests:
      storage: 50Gi