apiVersion: v1
data:
  Cache-Control: "no-cache, no-store, must-revalidate"
  Pragma: "no-cache"
  X-Content-Type-Options: "nosniff"
  X-Frame-Options: "deny"
  X-XSS-Protection: "1; mode=block"
  Content-Security-Policy: "default-src 'self' 'unsafe-inline' data: *.botiumbox.com botium.ai *.botium.ai"
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: ingress-nginx
