apiVersion: v1
kind: Secret
metadata:
  name: botium-box-secrets
  labels:
    name: secrets
    app: botium-box
stringData:
  COACH_WORKER_APIKEY: "{{ .Values.COACH_WORKER_APIKEY }}"
  BOTIUMBOX_SENTRY_DSN: "{{ .Values.BOTIUMBOX_SENTRY_DSN }}"
type: Opaque
