apiVersion: v1
kind: ConfigMap
metadata:
  name: botium-box-configmap
  labels:
    name: config
    app: botium-box
data:
  LICENSE_KEY: "{{ .Values.LICENSE_KEY }}"
  SEED_PASSWORD: "{{ .Values.SEED_PASSWORD }}"
  PRISMA_ENDPOINT: "{{ .Values.PRISMA_ENDPOINT }}"
  PRISMA_SECRET: "{{ .Values.PRISMA_SECRET }}"
  BOTIUMBOX_QUEUE_REDISURL: redis://redis:6379
  ZAP_ENDPOINT: http://zap:8080
  MYSQL_ROOT_PASSWORD: prisma
  PRISMA_CONFIG: |
    port: 4466
    databases:
      default:
        connector: mysql
        host: mysql
        port: 3306
        user: root
        password: prisma
        migrations: true
