apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: box-server
  labels:
    name: box-server
    app: botium-box
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: box-server
        app: botium-box
        tier: frontend
    spec:
      initContainers:
        - name: box-server-chmod-er
          image: busybox:latest
          command:
          - /bin/chown
          - -R
          - "1000:1000"
          - /app/server/storage
          volumeMounts:
          - mountPath: "/app/server/storage"
            name: botium-box-storage   
      containers:
        - name: box-server
          image: botium/botium-box-server:{{ .Values.BOTIUM_BOX_VERSION }}
          ports:
            - name: box-4000
              containerPort: 4000
          volumeMounts:
          - mountPath: "/app/server/storage/"
            name: botium-box-storage
          env:
            - name: DEBUG
              value: botium*
            - name: TESTSETDIR
              value: /app/server/storage/testsets
            - name: TESTSETDIR_PUBLIC
              value: /app/server/storage/testsets
            - name: RESOURCESDIR
              value: /app/server/storage/resources
            - name: BOTIUM_TEMPDIR
              value: /app/server/storage/botiumwork
            - name: PRISMA_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: PRISMA_ENDPOINT
            - name: PRISMA_SECRET
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: PRISMA_SECRET
            - name: LICENSE_KEY
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: LICENSE_KEY
            - name: BOTIUMBOX_QUEUE_REDISURL
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_QUEUE_REDISURL
            - name: ZAP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: ZAP_ENDPOINT
            - name: COACH_WORKER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: COACH_WORKER_ENDPOINT
            - name: COACH_WORKER_APIKEY
              valueFrom:
                configMapKeyRef:
                  name: botium-box-secrets
                  key: COACH_WORKER_APIKEY
            - name: BOTIUMBOX_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: BOTIUMBOX_SENTRY_DSN                  
      volumes:
        - name: botium-box-storage
          persistentVolumeClaim:
            claimName: botium-box-storage
---
apiVersion: v1
kind: Service
metadata:
  name: box-server
spec:
  ports:
    - port: 4000
  selector:
    name: box-server
    app: botium-box
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: box-agent
  labels:
    name: box-agent
    app: botium-box
    tier: frontend
spec:
  serviceName: "box-agent"
  replicas: {{ .Values.AGENT_COUNT }}
  selector:
    matchLabels:
      name: box-agent
  template:
    metadata:
      labels:
        name: box-agent
        app: botium-box
        tier: frontend
    spec:
      initContainers:
        - name: box-agent-chmod-er
          image: busybox:latest
          command:
          - /bin/chown
          - -R
          - "1000:1000"
          - /app/agent/storage
          volumeMounts:
          - mountPath: "/app/agent/storage"
            name: botium-box-storage
      containers:
        - name: box-agent
          image: botium/botium-box-agent:{{ .Values.BOTIUM_BOX_VERSION }}
          volumeMounts:
          - mountPath: "/app/agent/storage/"
            name: botium-box-storage
          env:
            - name: BOTIUMBOX_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DEBUG
              value: botium*
            - name: RESOURCESDIR
              value: /app/agent/storage/resources
            - name: BOTIUM_TEMPDIR
              value: /app/agent/storage/botiumwork
            - name: BOTIUMBOX_QUEUE_REDISURL
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_QUEUE_REDISURL
      volumes:
        - name: botium-box-storage
          persistentVolumeClaim:
            claimName: botium-box-storage
---
apiVersion: v1
kind: Service
metadata:
  name: box-agent
spec:
  clusterIP: None
  selector:
    name: box-agent
    app: botium-box
