apiVersion: v1
kind: ConfigMap
metadata:
  name: botium-coach-worker-configmap
  labels:
    name: config
    app: botium-coach-worker
data:
  AUTH_APIKEYS: "{{ .Values.AUTH_APIKEYS }}"
  WEB_CONCURRENCY: "{{ .Values.WEB_CONCURRENCY }}"
