apiVersion: v1
kind: Secret
metadata:
  name: botium-coach-worker-secrets
  labels:
    name: secrets
    app: botium-coach-worker
stringData:
  AUTH_APIKEYS: "{{ .Values.AUTH_APIKEYS }}"
type: Opaque
