apiVersion: v1
kind: Secret
metadata:
  name: botium-coach-worker-secrets
  labels:
    name: secrets
    app: botium-coach-worker
stringData:
  AUTH_APIKEYS: "{{ .Values.AUTH_APIKEYS }}"
  PINECONE_API: "{{ .Values.PINECONE_API }}"
  PINECONE_ENVIRONMENT: "{{ .Values.PINECONE_ENVIRONMENT }}"
  PINECONE_INDEX: "{{ .Values.PINECONE_INDEX }}"
  OPEN_API: "{{ .Values.OPEN_API }}"
type: Opaque
