apiVersion: v1
kind: ConfigMap
metadata:
  name: botium-coach-worker-configmap
  labels:
    name: config
    app: botium-coach-worker
data:
  WEB_CONCURRENCY: "{{ .Values.WEB_CONCURRENCY }}"
  COACH_MAX_UTTERANCES_FOR_EMBEDDINGS: "{{ .Values.COACH_MAX_UTTERANCES_FOR_EMBEDDINGS }}"
