apiVersion: apps/v1
kind: Deployment
metadata:
  name: coach-worker
  labels:
    name: coach-worker
    app: botium-coach-worker
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: coach-worker
      app: botium-coach-worker
      tier: frontend
  template:
    metadata:
      labels:
        name: coach-worker
        app: botium-coach-worker
        tier: frontend
    spec:
      containers:
        - name: coach-worker
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "3Gi"
          image: botium/botium-coach-worker:{{ .Values.BOTIUM_COACH_WORKER_VERSION }}
          imagePullPolicy: Always
          ports:
            - name: worker-8080
              containerPort: 8080
          env:
            - name: AUTH_APIKEYS
              valueFrom:
                secretKeyRef:
                  name: botium-coach-worker-secrets
                  key: AUTH_APIKEYS
            - name: WEB_CONCURRENCY
              valueFrom:
                configMapKeyRef:
                  name: botium-coach-worker-configmap
                  key: WEB_CONCURRENCY
            - name: COACH_MAX_UTTERANCES_FOR_EMBEDDINGS
              valueFrom:
                configMapKeyRef:
                  name: botium-coach-worker-configmap
                  key: COACH_MAX_UTTERANCES_FOR_EMBEDDINGS
---
{{- if not .Values.MINIKUBE }}
apiVersion: autoscaling/v1
{{- else }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: coach-worker-memory-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coach-worker
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageValue: "2.7Gi"
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: coach-worker
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: coach-worker
    app: botium-coach-worker
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coach-worker-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    rancher.io/globalDNS.hostname: {{ .Values.SHORTNAME }}.botiumbox.com
    cert-manager.io/cluster-issuer: {{ .Values.SHORTNAME }}-letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.SHORTNAME }}.botiumbox.com
    secretName: {{ .Values.SHORTNAME }}.botiumbox-com-tls
  rules:
  - host: {{ .Values.SHORTNAME }}.botiumbox.com
    http:
      paths:
      - path: /
        backend:
          serviceName: coach-worker
          servicePort: 8080
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ .Values.SHORTNAME }}-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: florian.treml@botium.at
    privateKeySecretRef:
      name: {{ .Values.SHORTNAME }}-letsencrypt-prod
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.SHORTNAME }}.botiumbox-com
spec:
  secretName: {{ .Values.SHORTNAME }}.botiumbox-com-tls
  issuerRef:
    name: {{ .Values.SHORTNAME }}-letsencrypt-prod
  commonName: {{ .Values.SHORTNAME }}.botiumbox.com
  dnsNames:
  - {{ .Values.SHORTNAME }}.botiumbox.com
