apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-admin
  labels:
    name: mysql-admin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: mysql-admin
  template:
    metadata:
      labels:
        name: mysql-admin
    spec:
      containers:
        - name: mysql-admin
          image: adminer
          ports:
            - name: admin-8080
              containerPort: 8080
          env:
            - name: ADMINER_DEFAULT_SERVER
              valueFrom:
                secretKeyRef:
                  name: botium-box-prisma
                  key: MYSQL_SERVER
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-admin
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: mysql-admin
