apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prisma-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    rancher.io/globalDNS.hostname: {{ .Values.FQDN }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.FQDN }}
    secretName: botiumbox-com-tls
  rules:
  - host: {{ .Values.FQDN }}
    http:
      paths:
      - path: /mysql-admin
        backend:
          serviceName: mysql-admin
          servicePort: 8080
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: florian.treml@botium.at
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: botiumbox-com
spec:
  secretName: botiumbox-com-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: {{ .Values.FQDN }}
  dnsNames:
  - {{ .Values.FQDN }}
