apiVersion: v1
kind: Secret
metadata:
  name: botium-box-secrets
  labels:
    name: secrets
    app: botium-box
stringData:
  LICENSE_KEY: "{{ .Values.LICENSE_KEY }}"
  DATABASE_URL: "{{ .Values.DATABASE_URL }}"
  SEED_ADMIN_EMAIL: "{{ .Values.SEED_ADMIN_EMAIL }}"
  SEED_PASSWORD: "{{ .Values.SEED_PASSWORD }}"
  {{- if .Values.BOTIUMBOX_QUEUE_SETTINGS }}
  BOTIUMBOX_QUEUE_SETTINGS: "{{ .Values.BOTIUMBOX_QUEUE_SETTINGS }}"
  BOTIUMBOX_QUEUE_REDISURL: ""
  {{- else if .Values.REDIS_SENTINEL_HOST }}
  BOTIUMBOX_QUEUE_SETTINGS: "{ \"redis\": { \"sentinels\": [{\"host\": \"{{ .Values.REDIS_SENTINEL_HOST }}\", \"port\": {{ .Values.REDIS_SENTINEL_PORT }} }], \"sentinelPassword\": \"{{ .Values.REDIS_PASSWORD }}\", \"password\": \"{{ .Values.REDIS_PASSWORD }}\", \"name\": \"{{ .Values.REDIS_SENTINEL_NAME }}\" } }"
  BOTIUMBOX_QUEUE_REDISURL: ""
  {{- else }}
  BOTIUMBOX_QUEUE_REDISURL: "redis://:{{ .Values.REDIS_PASSWORD }}@{{ .Values.REDIS_HOST }}:{{ .Values.REDIS_PORT }}/{{ .Values.REDIS_SELECT_INDEX }}"
  BOTIUMBOX_QUEUE_SETTINGS: ""
  {{- end }}
  SMTP_USER: "{{ .Values.SMTP_USER }}"
  SMTP_PASSWORD: "{{ .Values.SMTP_PASSWORD }}"
  COACH_WORKER_APIKEY: "{{ .Values.COACH_WORKER_APIKEY }}"
  SPEECH_PROCESSING_APIKEY: "{{ .Values.SPEECH_PROCESSING_APIKEY }}"
  BOTIUMBOX_SMARTLOOK_KEY: "{{ .Values.BOTIUMBOX_SMARTLOOK_KEY }}"
  BOTIUMBOX_SENTRY_DSN: "{{ .Values.BOTIUMBOX_SENTRY_DSN }}"
  BOTIUMBOX_PASSPORT_STRATEGY: "{{ .Values.BOTIUMBOX_PASSPORT_STRATEGY }}"
  BOTIUMBOX_PASSPORT_ADMINPASSWORD_HASH: "{{ .Values.BOTIUMBOX_PASSPORT_ADMINPASSWORD_HASH }}"
  BOTIUMBOX_ADMIN_APIKEY: "{{ .Values.BOTIUMBOX_ADMIN_APIKEY }}"
  GOOGLE_TRANSLATE_CLIENT_EMAIL: "{{ .Values.GOOGLE_TRANSLATE_CLIENT_EMAIL }}"
  GOOGLE_TRANSLATE_PRIVATE_KEY: "{{ .Values.GOOGLE_TRANSLATE_PRIVATE_KEY }}"
  OPENAI_APIKEY: "{{ .Values.OPENAI_APIKEY }}"
  OPENAI_RATE_BY_MINUTE: "{{ .Values.OPENAI_RATE_BY_MINUTE }}"  
  S3_ACCESS_KEY_ID: "{{ .Values.S3_ACCESS_KEY_ID }}"
  S3_SECRET_ACCESS_KEY: "{{ .Values.S3_SECRET_ACCESS_KEY }}"
  JWT_SECRET: "{{ .Values.JWT_SECRET }}"
type: Opaque
