apiVersion: v1
kind: ConfigMap
metadata:
  name: botium-box-configmap
  labels:
    name: config
    app: botium-box
data:
  BOTIUMBOX_QUEUE_PREFIX: "{{ .Values.BOTIUMBOX_QUEUE_PREFIX }}"
  BOTIUMBOX_AGENT_COUNT: "{{ .Values.BOTIUMBOX_AGENT_COUNT }}"
  SMTP_HOST: "{{ .Values.SMTP_HOST }}"
  SMTP_PORT: "{{ .Values.SMTP_PORT }}"
  {{- if .Values.SMTP_SECURE }}
  SMTP_SECURE: "1"
  {{- end }}
  COACH_WORKER_ENDPOINT: "{{ .Values.COACH_WORKER_ENDPOINT }}"
  SPEECH_PROCESSING_ENDPOINT: "{{ .Values.SPEECH_PROCESSING_ENDPOINT }}"  
  JWT_EXPIRY_MINUTES: "{{ .Values.JWT_EXPIRY_MINUTES }}"
  ZAP_ENDPOINT: "{{ .Values.ZAP_ENDPOINT }}"
  {{- if .Values.BOTIUMBOX_LOG_JSON }}
  BOTIUMBOX_LOG_JSON: "1"
  {{- else }}
  BOTIUMBOX_LOG_JSON: "0"
  {{- end }}
  BOTIUMBOX_FQDN: "{{ .Values.FQDN }}"
