apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: box-backup-cronjob
spec:
  schedule: {{ .Values.CRON_EXPRESSION }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: box-backup
            image: imega/mysql-client:latest
            args:
            - /bin/sh
            - -c
            - set -x && NOW=$(date +%Y%m%d_%H%M%S) && mkdir /app/backup/$NOW && mysqldump --user=root --password="${MYSQL_ROOT_PASSWORD}" --host=mysql "${BACKUP_DBNAME}" > /app/backup/$NOW/"${BACKUP_DBNAME}".sql && gzip /app/backup/$NOW/"${BACKUP_DBNAME}".sql && echo Backup to /app/backup/$NOW/ ready.
            volumeMounts:
            - mountPath: "/app/storage"
              name: botium-box-storage
            - mountPath: "/app/mysql"
              name: mysql-storage
            - mountPath: "/app/backup"
              name: backup-storage
            env:
              - name: BACKUP_DBNAME
                value: {{ .Values.BACKUP_DBNAME }}
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    name: botium-box-configmap
                    key: MYSQL_ROOT_PASSWORD
          volumes:
          - name: botium-box-storage
            persistentVolumeClaim:
              claimName: botium-box-storage
          - name: mysql-storage
            persistentVolumeClaim:
              claimName: mysql-storage
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-storage
          restartPolicy: OnFailure
