{{- $root := . -}}

{{- range .Values.SERVICES }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .SERVICE_NAME }}
spec:
  type: ExternalName
  externalName: {{ .SERVICE_NAME_EXTERNAL }}
{{- end}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wildcard-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.SHORTNAME }}-letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.SHORTNAME }}.botiumbox.com
    - '*.{{ .Values.SHORTNAME }}.botiumbox.com'
    secretName: {{ .Values.SHORTNAME }}.botiumbox-com-tls
  rules:
  {{- range .Values.SERVICES }}
  - host: '{{ .SERVICE_SUBDOMAIN }}.{{ $root.Values.SHORTNAME }}.botiumbox.com'
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .SERVICE_NAME }}
          servicePort: {{ .SERVICE_PORT }}
  {{- end}}
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Values.SHORTNAME }}-letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: florian.treml@botium.at
    privateKeySecretRef:
      name: {{ .Values.SHORTNAME }}-letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - '*.{{ .Values.SHORTNAME }}.botiumbox.com'
      dns01:
        route53:
          region: eu-west-1
          accessKeyID: "{{ .Values.AWS_ACCESS_KEY_ID }}"
          secretAccessKeySecretRef:
            name: botium-box-secrets
            key: AWS_SECRET_ACCESS_KEY
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.SHORTNAME }}.botiumbox-com
  namespace: cert-manager
spec:
  secretName: {{ .Values.SHORTNAME }}.botiumbox-com-tls
  issuerRef:
    name: {{ .Values.SHORTNAME }}-letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - '*.{{ .Values.SHORTNAME }}.botiumbox.com'
  acme:
    config:
      - dns01:
          provider: route53
        domains:
          - '*.{{ .Values.SHORTNAME }}.botiumbox.com'
