---
# Source: botium-box-advanced/templates/08-agents.yml
apiVersion: v1
kind: Service
metadata:
  name: box-agent
spec:
  clusterIP: None
  selector:
    name: box-agent
    app: botium-box
---
# Source: botium-box-advanced/templates/08-agents.yml
apiVersion: v1
kind: Service
metadata:
  name: box-agentp
spec:
  clusterIP: None
  selector:
    name: box-agentp
    app: botium-box
---
# Source: botium-box-advanced/templates/08-agents.yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: box-agent
  labels:
    name: box-agent
    app: botium-box
    tier: frontend
spec:
  serviceName: "box-agent"
  replicas: 10
  selector:
    matchLabels:
      name: box-agent
  template:
    metadata:
      labels:
        name: box-agent
        app: botium-box
        tier: frontend
    spec:
      initContainers:
        - name: box-agent-chmod-er
          image: busybox:latest
          command:
          - /bin/chown
          - -R
          - "1000:1000"
          - /app/agent/storage
          volumeMounts:
          - mountPath: "/app/agent/storage"
            name: botium-box-storage
      containers:
        - name: box-agent
          image: botium/botium-box-agent:2.8.7
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "./wait.sh -t $WAIT_TIMEOUT -e $BOTIUMBOX_QUEUE_REDISURL && npm run start:dist"]
          volumeMounts:
          - mountPath: "/app/server/storage/"
            name: botium-box-storage
          env:
            - name: BOTIUMBOX_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DEBUG
              value: botium*
            - name: RESOURCESDIR
              value: /app/server/storage/resources
            - name: BOTIUM_TEMPDIR
              value: /app/server/storage/botiumwork
            - name: BOTIUMBOX_QUEUE_CONCURRENCY
              value: "10"
            - name: BOTIUMBOX_QUEUE_CONCURRENCY_COACH
              value: "10"
            - name: BOTIUMBOX_QUEUE_CONCURRENCY_PERFORMANCE
              value: "0"
            - name: BOTIUMBOX_QUEUE_HEARTBEAT
              value: "0"
            - name: BOTIUMBOX_QUEUE_REDISURL
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: BOTIUMBOX_QUEUE_REDISURL
            - name: BOTIUMBOX_QUEUE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_QUEUE_PREFIX
      volumes:
        - name: botium-box-storage
          persistentVolumeClaim:
            claimName: botium-box-storage
---
# Source: botium-box-advanced/templates/08-agents.yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: box-agentp
  labels:
    name: box-agentp
    app: botium-box
    tier: frontend
spec:
  serviceName: "box-agentp"
  replicas: 5
  selector:
    matchLabels:
      name: box-agentp
  template:
    metadata:
      labels:
        name: box-agentp
        app: botium-box
        tier: frontend
    spec:
      initContainers:
        - name: box-agentp-chmod-er
          image: busybox:latest
          command:
          - /bin/chown
          - -R
          - "1000:1000"
          - /app/agent/storage
          volumeMounts:
          - mountPath: "/app/agent/storage"
            name: botium-box-storage
      containers:
        - name: box-agentp
          image: botium/botium-box-agent:2.8.7
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "./wait.sh -t $WAIT_TIMEOUT -e $BOTIUMBOX_QUEUE_REDISURL && npm run start:dist"]
          volumeMounts:
          - mountPath: "/app/server/storage/"
            name: botium-box-storage
          env:
            - name: BOTIUMBOX_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DEBUG
              value: botium*
            - name: RESOURCESDIR
              value: /app/server/storage/resources
            - name: BOTIUM_TEMPDIR
              value: /app/server/storage/botiumwork
            - name: BOTIUMBOX_QUEUE_CONCURRENCY
              value: "0"
            - name: BOTIUMBOX_QUEUE_CONCURRENCY_COACH
              value: "0"
            - name: BOTIUMBOX_QUEUE_CONCURRENCY_PERFORMANCE
              value: "10"
            - name: BOTIUMBOX_QUEUE_HEARTBEAT
              value: "0"
            - name: BOTIUMBOX_QUEUE_REDISURL
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: BOTIUMBOX_QUEUE_REDISURL
            - name: BOTIUMBOX_QUEUE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_QUEUE_PREFIX
      volumes:
        - name: botium-box-storage
          persistentVolumeClaim:
            claimName: botium-box-storage
