{{- if .Values.ENABLE_S3_BACKUP }}
apiVersion: v1
kind: Secret
metadata:
  name: prisma-backup-secrets
  labels:
    name: secrets
    app: prisma-backup-scheduler
stringData:
  S3_ACCESS_KEY_ID: "{{ .Values.S3_ACCESS_KEY_ID }}"
  S3_SECRET_ACCESS_KEY: "{{ .Values.S3_SECRET_ACCESS_KEY }}"
type: Opaque
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: prisma-backup-scheduler
spec:
  schedule: "{{ .Values.BACKUP_SCHEDULE }}"
  concurrencyPolicy: "Forbid"
  jobTemplate:
    parallelism: 1
    completions: 1
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup-s3
            image: murliwatz/mysql-backup-s3
            env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: botium-box-prisma
                  key: MYSQL_SERVER
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: botium-box-prisma
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: botium-box-prisma
                  key: MYSQL_ROOT_PASSWORD
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: prisma-backup-secrets
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: prisma-backup-secrets
                  key: S3_SECRET_ACCESS_KEY
            - name: MULTI_FILES
              value: "yes"
            - name: S3_BUCKET
              value: "{{ .Values.S3_BUCKET }}"
            - name: S3_PREFIX
              value: "{{ .Values.FQDN }}"
            - name: S3_REGION
              value: "{{ .Values.S3_REGION }}"
            - name: S3_ENDPOINT
              value: "{{ .Values.S3_ENDPOINT }}"
            - name: DB_SIZE_THRESHOLD
              value: "{{ .Values.DB_SIZE_THRESHOLD }}"
          restartPolicy: OnFailure
{{- end }}
