apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    name: phpmyadmin
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin:latest
          ports:
            - name: phpmyadmin-80
              containerPort: 80
          env:
            - name: PMA_HOST
              valueFrom:
                secretKeyRef:
                  name: botium-box-prisma
                  key: MYSQL_SERVER
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: botium-box-prisma
                  key: MYSQL_USER
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: phpmyadmin
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: phpmyadmin-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    rancher.io/globalDNS.hostname: {{ .Values.FQDN_PHPMYADMIN }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.FQDN_PHPMYADMIN }}
    secretName: phpmyadmin-botiumbox-com-tls
  rules:
  - host: {{ .Values.FQDN_PHPMYADMIN }}
    http:
      paths:
      - path: /
        backend:
          serviceName: phpmyadmin
          servicePort: 80
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: phpmyadmin-botiumbox-com
spec:
  secretName: phpmyadmin-botiumbox-com-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: {{ .Values.FQDN_PHPMYADMIN }}
  dnsNames:
  - {{ .Values.FQDN_PHPMYADMIN }}
