{{- if .Values.NEWER_KUBERNETES }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: prisma
  labels:
    name: prisma
spec:
  replicas: 1
  strategy:
    type: Recreate
  {{- if .Values.NEWER_KUBERNETES }}
  selector:
    matchLabels:
      name: prisma
  {{- end }}
  template:
    metadata:
      labels:
        name: prisma
    spec:
      containers:
        - name: prisma
          image: prismagraphql/prisma:{{ .Values.PRISMA_VERSION }}
          ports:
            - name: prisma-4466
              containerPort: 4466
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                secretKeyRef:
                  name: botium-box-prisma
                  key: PRISMA_CONFIG
---
apiVersion: v1
kind: Service
metadata:
  name: prisma
spec:
  ports:
    - port: 4466
      targetPort: 4466
      protocol: TCP
  selector:
    name: prisma
{{- if .Values.INSTALL_INGRESS }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prisma-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    rancher.io/globalDNS.hostname: {{ .Values.FQDN }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.FQDN }}
    secretName: botiumbox-com-tls
  rules:
  - host: {{ .Values.FQDN }}
    http:
      paths:
      - path: /
        backend:
          serviceName: prisma
          servicePort: 4466
      - path: /mysql-admin
        backend:
          serviceName: mysql-admin
          servicePort: 8080
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: florian.treml@botium.at
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: botiumbox-com
spec:
  secretName: botiumbox-com-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: {{ .Values.FQDN }}
  dnsNames:
  - {{ .Values.FQDN }}
{{- end }}
