{{- if .Values.INSTALL_INGRESS }}
{{- if .Values.USE_LETSENCRYPT }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prisma-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    rancher.io/globalDNS.hostname: {{ .Values.FQDN }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.FQDN }}
    secretName: botiumbox-tls
  rules:
  - host: {{ .Values.FQDN }}
    http:
      paths:
      - path: /mysql-admin
        backend:
          serviceName: mysql-admin
          servicePort: 8080
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.LETS_ENCRYPT_EMAIL }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: botiumbox
spec:
  secretName: botiumbox-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: {{ .Values.FQDN }}
  dnsNames:
  - {{ .Values.FQDN }}
{{- end }}
{{- if .Values.USE_AWS_ALB}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prisma-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    rancher.io/globalDNS.hostname: {{ .Values.FQDN }}
spec:
  ingressClassName: alb
  rules:
  - host: {{ .Values.FQDN }}
    http:
      paths:
      - path: /mysql-admin
        backend:
          serviceName: mysql-admin
          servicePort: 8080
{{- end }}
{{- end }}
