apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma
  labels:
    name: prisma
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: prisma
  template:
    metadata:
      labels:
        name: prisma
    spec:
      initContainers:
        - name: prisma-wait-rabbitmq
          image: martin/wait
          args: ["-c", "rabbitmq:5672", "-t", "30"]
      containers:
        - name: prisma
          image: prismagraphql/prisma-prod:{{ .Values.PRISMA_VERSION }}
          ports:
            - name: prisma-4466
              containerPort: 4466
          livenessProbe:
            httpGet:
              path: /
              port: prisma-4466
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: prisma-4466
            initialDelaySeconds: 10
            failureThreshold: 10
            periodSeconds: 10
          env:
            - name: SLOW_QUERIES_LOGGING
              value: "true"
            - name: PRISMA_CONFIG
              valueFrom:
                secretKeyRef:
                  name: botium-box-prisma
                  key: PRISMA_CONFIG_MANAGEMENT
---
apiVersion: v1
kind: Service
metadata:
  name: prisma
spec:
  ports:
    - port: 4466
      targetPort: 4466
      protocol: TCP
  selector:
    name: prisma
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma-worker
  labels:
    name: prisma-worker
spec:
  replicas: {{ .Values.PRISMA_WORKER_REPLICAS }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: prisma-worker
  template:
    metadata:
      labels:
        name: prisma-worker
    spec:
      initContainers:
        - name: prisma-worker-wait-rabbitmq
          image: martin/wait
          args: ["-c", "rabbitmq:5672", "-t", "30"]
      containers:
        - name: prisma-worker
          image: prismagraphql/prisma-prod:{{ .Values.PRISMA_VERSION }}
          ports:
            - name: prisma-w-4466
              containerPort: 4466
          livenessProbe:
            httpGet:
              path: /
              port: prisma-w-4466
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: prisma-w-4466
            initialDelaySeconds: 10
            failureThreshold: 10
            periodSeconds: 10
          env:
            - name: SLOW_QUERIES_LOGGING
              value: "true"
            - name: PRISMA_CONFIG
              valueFrom:
                secretKeyRef:
                  name: botium-box-prisma
                  key: PRISMA_CONFIG_WORKER
---
apiVersion: v1
kind: Service
metadata:
  name: prisma-worker
spec:
  ports:
    - port: 4466
      targetPort: 4466
      protocol: TCP
  selector:
    name: prisma-worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma-service-worker
  labels:
    name: prisma-service-worker
spec:
  replicas: {{ .Values.PRISMA_SERVICE_WORKER_REPLICAS }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: prisma-service-worker
  template:
    metadata:
      labels:
        name: prisma-service-worker
    spec:
      initContainers:
        - name: prisma-service-worker-wait-rabbitmq
          image: martin/wait
          args: ["-c", "rabbitmq:5672", "-t", "30"]
      containers:
        - name: prisma-service-worker
          image: prismagraphql/prisma-prod:{{ .Values.PRISMA_VERSION }}
          ports:
            - name: prisma-w-4466
              containerPort: 4466
          livenessProbe:
            httpGet:
              path: /
              port: prisma-w-4466
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: prisma-w-4466
            initialDelaySeconds: 10
            failureThreshold: 10
            periodSeconds: 10
          env:
            - name: SLOW_QUERIES_LOGGING
              value: "true"
            - name: PRISMA_CONFIG
              valueFrom:
                secretKeyRef:
                  name: botium-box-prisma
                  key: PRISMA_CONFIG_WORKER
---
apiVersion: v1
kind: Service
metadata:
  name: prisma-service-worker
spec:
  ports:
    - port: 4466
      targetPort: 4466
      protocol: TCP
  selector:
    name: prisma-service-worker
{{- if .Values.INSTALL_INGRESS }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prisma-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    rancher.io/globalDNS.hostname: {{ .Values.FQDN }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - {{ .Values.FQDN }}
    secretName: botiumbox-tls
  rules:
  - host: {{ .Values.FQDN }}
    http:
      paths:
      - path: /
        backend:
          serviceName: prisma
          servicePort: 4466
      - path: /mysql-admin
        backend:
          serviceName: mysql-admin
          servicePort: 8080
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.LETS_ENCRYPT_EMAIL }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: botiumbox
spec:
  secretName: botiumbox-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: {{ .Values.FQDN }}
  dnsNames:
  - {{ .Values.FQDN }}
{{- end }}
