apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prisma
  labels:
    name: prisma
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: prisma
    spec:
      containers:
        - name: prisma
          image: prismagraphql/prisma:{{ .Values.PRISMA_VERSION }}
          ports:
            - name: prisma-4466
              containerPort: 4466
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                secretKeyRef:
                  name: botium-box-prisma
                  key: PRISMA_CONFIG
---
apiVersion: v1
kind: Service
metadata:
  name: prisma
spec:
  ports:
    - port: 4466
      targetPort: 4466
      protocol: TCP
  selector:
    name: prisma