apiVersion: v1
kind: Secret
metadata:
  name: botium-box-prisma
stringData:
  MYSQL_SERVER: {{ .Values.MYSQL_HOST }}
  MYSQL_USER: {{ .Values.MYSQL_USER }}
  MYSQL_ROOT_PASSWORD: {{ .Values.MYSQL_PASSWORD }}
type: Opaque
