apiVersion: v1
kind: Secret
metadata:
  name: botium-box-prisma
stringData:
  MYSQL_SERVER: {{ .Values.MYSQL_HOST }}
  MYSQL_USER: {{ .Values.MYSQL_USER }}
  MYSQL_ROOT_PASSWORD: {{ .Values.MYSQL_PASSWORD }}
  PRISMA_CONFIG: |
    managementApiSecret: {{ .Values.PRISMA_MANAGEMENT_API_SECRET }}
    port: 4466
    databases:
      default:
        managementSchema: {{ .Values.PRISMA_MANAGEMENT_SCHEMA }}
        connector: mysql
        host: {{ .Values.MYSQL_HOST }}
        port: 3306
        user: {{ .Values.MYSQL_USER }}
        password: {{ .Values.MYSQL_PASSWORD }}
        migrations: true
type: Opaque
