apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botium-box-storage
  namespace: botium-box
  labels:
    name: botium-box-storage
    app: botium-box
    tier: frontend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: botium-box-storage-class
  resources:
    requests:
      storage: 5Gi
