apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zap
  namespace: botium-box
  labels:
    name: zap
    app: botium-box
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: zap
        app: botium-box
        tier: backend
    spec:
      containers:
        - name: zap
          image: owasp/zap2docker-stable:latest
          command: [
            "zap.sh",
            "-daemon",
            "-host", "0.0.0.0", "-port", "8080",
            "-config", "api.disablekey=true",
            "-config", "api.addrs.addr.name=.*",
            "-config", "api.addrs.addr.regex=true"
          ]		  
          ports:
            - name: zap-8080
              containerPort: 8080	  
---
apiVersion: v1
kind: Service
metadata:
  name: zap
  namespace: botium-box
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: zap
    app: botium-box