# Optional, but mandatory in query.yaml. In /k8s can it be "" for smoketesting (because starting the app without domain name is much faster).
FQDN: ""
BOTIUM_SPEECH_PROCESSING_VERSION: "latest"
AUTH_APIKEYS: ""
# if the helm chart is not deployed using Rancher but first converted to kubernetes workload, then features of Rancher will be disabled
# in questions.yaml is not there because its set to true here, and to false in /k8s dir
USE_RANCHER: true
BOTIUM_SPEECH_PROVIDER_TTS: "picotts"
BOTIUM_SPEECH_PROVIDER_STT: "kaldi"
BOTIUM_SPEECH_GOOGLE_CLIENT_EMAIL: ""
BOTIUM_SPEECH_GOOGLE_PRIVATE_KEY: ""
BOTIUM_SPEECH_PROCESSING_STORAGE_CLASS: "aws-efs"
