SHORTNAME: ""
BOTIUM_SPEECH_PROCESSING_VERSION: "latest"
AUTH_APIKEYS: ""
BOTIUM_SPEECH_PROVIDER_TTS: "marytts"
BOTIUM_SPEECH_PROVIDER_STT: "kaldi"
BOTIUM_SPEECH_GOOGLE_CLIENT_EMAIL: ""
BOTIUM_SPEECH_GOOGLE_PRIVATE_KEY: ""
STORAGE_CLASS_SPEECH_PROCESSING: ""
BOTIUM_SPEECH_PROCESSING_STORAGE_CLASS: "aws-efs"
