apiVersion: v1
kind: Secret
metadata:
  name: botium-box-secrets
  labels:
    name: secrets
    app: botium-box  
stringData:
  LICENSE_KEY: "{{ .Values.LICENSE_KEY }}"
  PRISMA_MANAGEMENT_API_SECRET: "{{ .Values.PRISMA_MANAGEMENT_API_SECRET }}"
  PRISMA_SECRET: "{{ .Values.PRISMA_SECRET }}"
  SEED_PASSWORD: "{{ .Values.SEED_PASSWORD }}"
  BOTIUMBOX_QUEUE_REDISURL: redis://:{{ .Values.REDIS_PASSWORD }}@redis:6379
type: Opaque
