{{- if .Values.INSTALL_REDIS }}
{{- if .Values.NEWER_KUBERNETES }}
apiVersion: apps/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: redis
  labels:
    name: redis
    app: botium-box
    tier: backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  {{- if .Values.NEWER_KUBERNETES }}
  selector:
    matchLabels:
      name: redis
      app: botium-box
  {{- end }}
  template:
    metadata:
      labels:
        name: redis
        app: botium-box
        tier: backend
    spec:
      containers:
        - name: redis
          image: redis:alpine
          command: ["redis-server"]
          args: ["--requirepass", "{{ .Values.REDIS_PASSWORD }}"]
          ports:
            - name: redis-6379
              containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    name: redis
    app: botium-box
{{- end}}
