apiVersion: v2
name: botium-box-redis
description: Redis for Botium Box

type: application
version: 1.0.0-v2
appVersion: 15.5.4

dependencies:
  - name: redis
    version: 15.5.4
    repository: https://charts.bitnami.com/bitnami