apiVersion: v2
name: botium-box-redis
description: Redis for Botium Box

type: application
version: 1.1.0-v0
appVersion: 15.4.0-v1

dependencies:
  - name: redis
    version: 15.4.0
    repository: https://charts.bitnami.com/bitnami