kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-efs
provisioner: botiumbox.com/aws-efs
{{- if .Values.SYNC }}
mountOptions:
  - sync
{{- else }}
mountOptions:
  - noresvport
  - rsize=1048576
  - wsize=1048576
  - hard
  - timeo=600
  - retrans=2
  - _netdev
  - nofail
{{- end }}
