apiVersion: v1
kind: ConfigMap
metadata:
  name: botium-box-configmap
  labels:
    name: config
    app: botium-box
data:
  LICENSE_KEY: "{{ .Values.LICENSE_KEY }}"
  PRISMA_ENDPOINT: "{{ .Values.PRISMA_ENDPOINT }}"
  PRISMA_SECRET: "{{ .Values.PRISMA_SECRET }}"
  PRISMA_CLOUD_SESSION_KEY: "{{ .Values.PRISMA_CLOUD_SESSION_KEY }}"
  SEED_PASSWORD: "{{ .Values.SEED_PASSWORD }}"
  BOTIUMBOX_QUEUE_REDISURL: redis://:{{ .Values.REDIS_PASSWORD }}@redis:6379