---
# Source: botium-box-advanced/templates/03-volumes.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botium-box-storage
  labels:
    name: botium-box-storage
    app: botium-box
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: 
  resources:
    requests:
      storage: 20Gi
---
# Source: botium-box-advanced/templates/03-volumes.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botium-box-prisma-config-storage
  labels:
    name: botium-box-prisma-config-storage
    app: botium-box
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: 
  resources:
    requests:
      storage: 20Gi
