apiVersion: v1
kind: Secret
metadata:
  name: botium-box-secrets
  labels:
    name: secrets
    app: botium-box
stringData:
  LICENSE_KEY: "{{ .Values.LICENSE_KEY }}"
  {{- if .Values.DATABASE_CERT }}
  {{- if contains "?" .Values.DATABASE_URL }}
  DATABASE_URL: "{{ .Values.DATABASE_URL }}&sslcert=/app/prisma-cert/sslcert.pem"
  {{- else }}
  DATABASE_URL: "{{ .Values.DATABASE_URL }}?sslcert=/app/prisma-cert/sslcert.pem"
  {{- end }}
  NODE_EXTRA_CA_CERTS: |
{{ .Values.NODE_EXTRA_CA_CERTS | indent 4 }}
  DATABASE_CERT: |
{{ .Values.DATABASE_CERT | indent 4 }}
  {{- else }}
  DATABASE_URL: "{{ .Values.DATABASE_URL }}"
  DATABASE_CERT: ""
  {{- end }}
  BOTIUMBOX_QUEUE_SETTINGS: "{{ .Values.BOTIUMBOX_QUEUE_SETTINGS }}"
  BOTIUMBOX_QUEUE_REDISURL: "{{ .Values.BOTIUMBOX_QUEUE_REDISURL }}"
  SMTP_USER: "{{ .Values.SMTP_USER }}"
  SMTP_PASSWORD: "{{ .Values.SMTP_PASSWORD }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.AWS_SECRET_ACCESS_KEY }}"
  COACH_WORKER_APIKEY: "{{ .Values.COACH_WORKER_APIKEY }}"
  SPEECH_PROCESSING_APIKEY: "{{ .Values.SPEECH_PROCESSING_APIKEY }}"
  BOTIUMBOX_SENTRY_DSN: "{{ .Values.BOTIUMBOX_SENTRY_DSN }}"
  BOTIUMBOX_PASSPORT_STRATEGY: "{{ .Values.BOTIUMBOX_PASSPORT_STRATEGY }}"
  BOTIUMBOX_PASSPORT_ADMINPASSWORD_HASH: "{{ .Values.BOTIUMBOX_PASSPORT_ADMINPASSWORD_HASH }}"
  BOTIUMBOX_ADMIN_APIKEY: "{{ .Values.BOTIUMBOX_ADMIN_APIKEY }}"
  GOOGLE_TRANSLATE_CLIENT_EMAIL: "{{ .Values.GOOGLE_TRANSLATE_CLIENT_EMAIL }}"
  GOOGLE_TRANSLATE_PRIVATE_KEY: |
{{ .Values.GOOGLE_TRANSLATE_PRIVATE_KEY | indent 4 }}  
  OPENAI_APIKEY: "{{ .Values.OPENAI_APIKEY }}"
  JWT_SECRET: "{{ .Values.JWT_SECRET }}"
type: Opaque
