apiVersion: v1
kind: Secret
metadata:
  name: botium-box-secrets
  labels:
    name: secrets
    app: botium-box
stringData:
  LICENSE_KEY: "{{ .Values.LICENSE_KEY }}"
  PRISMA_SECRET: "{{ .Values.PRISMA_SECRET }}"
  PRISMA_MANAGEMENT_API_SECRET: "{{ .Values.PRISMA_MANAGEMENT_API_SECRET }}"
  BOTIUMBOX_QUEUE_REDISURL: "redis://:{{ .Values.REDIS_PASSWORD }}@{{ .Values.REDIS_SERVICE }}:6379/{{ .Values.REDIS_SELECT_INDEX }}"
  SMTP_USER: "{{ .Values.SMTP_USER }}"
  SMTP_PASSWORD: "{{ .Values.SMTP_PASSWORD }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.AWS_SECRET_ACCESS_KEY }}"
  JWT_SECRET: "{{ .Values.JWT_SECRET }}"
  COACH_WORKER_APIKEY: "{{ .Values.COACH_WORKER_APIKEY }}"
  SPEECH_PROCESSING_APIKEY: "{{ .Values.SPEECH_PROCESSING_APIKEY }}"
  BITBUCKET_USERNAME: "{{ .Values.BITBUCKET_USERNAME }}"
  BITBUCKET_PASSWORD: "{{ .Values.BITBUCKET_PASSWORD }}"
  BOTIUMBOX_SMARTLOOK_KEY: "{{ .Values.BOTIUMBOX_SMARTLOOK_KEY }}"
  BOTIUMBOX_SENTRY_DSN: "{{ .Values.BOTIUMBOX_SENTRY_DSN }}"
  BOTIUMBOX_PASSPORT_ADMINPASSWORD: "{{ .Values.BOTIUMBOX_PASSPORT_ADMINPASSWORD }}"
  GOOGLE_TRANSLATE_CLIENT_EMAIL: "{{ .Values.GOOGLE_TRANSLATE_CLIENT_EMAIL }}"
  GOOGLE_TRANSLATE_PRIVATE_KEY: "{{ .Values.GOOGLE_TRANSLATE_PRIVATE_KEY }}"
  PARAPHRASING_APIKEY: "{{ .Values.PARAPHRASING_APIKEY }}"
  S3_ACCESS_KEY_ID: "{{ .Values.S3_ACCESS_KEY_ID }}"
  S3_SECRET_ACCESS_KEY: "{{ .Values.S3_SECRET_ACCESS_KEY }}"
type: Opaque
