apiVersion: v1
kind: Secret
metadata:
  name: botium-box-secrets
  labels:
    name: secrets
    app: botium-box
stringData:
  LICENSE_KEY: "{{ .Values.LICENSE_KEY }}"
  DATABASE_URL: "{{ .Values.DATABASE_URL }}"
  BOTIUMBOX_QUEUE_SETTINGS: "{{ .Values.BOTIUMBOX_QUEUE_SETTINGS }}"
  BOTIUMBOX_QUEUE_REDISURL: "{{ .Values.BOTIUMBOX_QUEUE_REDISURL }}"
  SMTP_USER: "{{ .Values.SMTP_USER }}"
  SMTP_PASSWORD: "{{ .Values.SMTP_PASSWORD }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.AWS_SECRET_ACCESS_KEY }}"
  COACH_WORKER_APIKEY: "{{ .Values.COACH_WORKER_APIKEY }}"
  SPEECH_PROCESSING_APIKEY: "{{ .Values.SPEECH_PROCESSING_APIKEY }}"
  BOTIUMBOX_SMARTLOOK_KEY: "{{ .Values.BOTIUMBOX_SMARTLOOK_KEY }}"
  BOTIUMBOX_SENTRY_DSN: "{{ .Values.BOTIUMBOX_SENTRY_DSN }}"
  BOTIUMBOX_PASSPORT_ADMINPASSWORD_HASH: "{{ .Values.BOTIUMBOX_PASSPORT_ADMINPASSWORD_HASH }}"
  BOTIUMBOX_ADMIN_APIKEY: "{{ .Values.BOTIUMBOX_ADMIN_APIKEY }}"
  GOOGLE_TRANSLATE_CLIENT_EMAIL: "{{ .Values.GOOGLE_TRANSLATE_CLIENT_EMAIL }}"
  GOOGLE_TRANSLATE_PRIVATE_KEY: "{{ .Values.GOOGLE_TRANSLATE_PRIVATE_KEY }}"
  OPENAI_APIKEY: "{{ .Values.OPENAI_APIKEY }}"
  OPENAI_RATE_BY_MINUTE: "{{ .Values.OPENAI_RATE_BY_MINUTE }}"
  JWT_SECRET: "{{ .Values.JWT_SECRET }}"
type: Opaque
