apiVersion: v1
kind: Secret
metadata:
  name: botium-box-secrets
  labels:
    name: secrets
    app: botium-box
stringData:
  LICENSE_KEY: "{{ .Values.LICENSE_KEY }}"
  DATABASE_URL: "{{ .Values.DATABASE_URL }}"
  {{- if .Values.REDIS_HOST }}
  BOTIUMBOX_QUEUE_REDISURL: "redis://:{{ .Values.REDIS_PASSWORD }}@{{ .Values.REDIS_HOST }}:{{ .Values.REDIS_PORT }}/{{ .Values.REDIS_SELECT_INDEX }}"
  {{- else }}
  BOTIUMBOX_QUEUE_REDISURL: ""
  {{- end }}
  {{- if .Values.REDIS_SENTINEL_HOST }}
  BOTIUMBOX_QUEUE_SETTINGS: "{ \"redis\": { \"sentinels\": [{\"host\": \"{{ .Values.REDIS_SENTINEL_HOST }}\", \"port\": {{ .Values.REDIS_SENTINEL_PORT }} }], \"sentinelPassword\": \"{{ .Values.REDIS_PASSWORD }}\", \"password\": \"{{ .Values.REDIS_PASSWORD }}\", \"name\": \"{{ .Values.REDIS_SENTINEL_NAME }}\" } }"
  {{- else if .Values.BOTIUMBOX_QUEUE_SETTINGS }}
  BOTIUMBOX_QUEUE_SETTINGS: "{{ .Values.BOTIUMBOX_QUEUE_SETTINGS }}"
  {{- else }}
  BOTIUMBOX_QUEUE_SETTINGS: ""
  {{- end }}
  SMTP_USER: "{{ .Values.SMTP_USER }}"
  SMTP_PASSWORD: "{{ .Values.SMTP_PASSWORD }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.AWS_SECRET_ACCESS_KEY }}"
  COACH_WORKER_APIKEY: "{{ .Values.COACH_WORKER_APIKEY }}"
  SPEECH_PROCESSING_APIKEY: "{{ .Values.SPEECH_PROCESSING_APIKEY }}"
  BOTIUMBOX_AUDIT_CRMAUTH_CLIENTID: "{{ .Values.BOTIUMBOX_AUDIT_CRMAUTH_CLIENTID }}"
  BOTIUMBOX_AUDIT_CRMAUTH_CLIENTSECRET: "{{ .Values.BOTIUMBOX_AUDIT_CRMAUTH_CLIENTSECRET }}"
  BITBUCKET_USERNAME: "{{ .Values.BITBUCKET_USERNAME }}"
  BITBUCKET_PASSWORD: "{{ .Values.BITBUCKET_PASSWORD }}"
  BOTIUMBOX_SMARTLOOK_KEY: "{{ .Values.BOTIUMBOX_SMARTLOOK_KEY }}"
  BOTIUMBOX_SENTRY_DSN: "{{ .Values.BOTIUMBOX_SENTRY_DSN }}"
  BOTIUMBOX_PASSPORT_ADMINPASSWORD: "{{ .Values.BOTIUMBOX_PASSPORT_ADMINPASSWORD }}"
  BOTIUMBOX_ADMIN_APIKEY: "{{ .Values.BOTIUMBOX_ADMIN_APIKEY }}"
  GOOGLE_TRANSLATE_CLIENT_EMAIL: "{{ .Values.GOOGLE_TRANSLATE_CLIENT_EMAIL }}"
  GOOGLE_TRANSLATE_PRIVATE_KEY: "{{ .Values.GOOGLE_TRANSLATE_PRIVATE_KEY }}"
  PARAPHRASING_APIKEY: "{{ .Values.PARAPHRASING_APIKEY }}"
  S3_ACCESS_KEY_ID: "{{ .Values.S3_ACCESS_KEY_ID }}"
  S3_SECRET_ACCESS_KEY: "{{ .Values.S3_SECRET_ACCESS_KEY }}"
  JWT_SECRET: "{{ .Values.JWT_SECRET }}"
type: Opaque
