apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botium-box-storage
  labels:
    name: botium-box-storage
    app: botium-box
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.STORAGE_CLASS_BOX }}
  resources:
    requests:
      storage: 20Gi
{{- if .Values.ENABLE_MULTI_TENANCY }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botium-box-prisma-config-storage
  labels:
    name: botium-box-prisma-config-storage
    app: botium-box
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.STORAGE_CLASS_BOX }}
  resources:
    requests:
      storage: 20Gi
{{- end }}
