apiVersion: v1
kind: Service
metadata:
  name: box-server
spec:
  ports:
    {{- if eq .Values.MAINTENANCE false }}
    - port: 4000
    {{- else }}
    - port: 4000
      targetPort: 80
      protocol: TCP
    {{- end }}
  selector:
    name: box-server
    app: botium-box
    {{- if eq .Values.MAINTENANCE false }}
    mode: live
    {{- else }}
    mode: maintenance
    {{- end }}
{{- if .Values.MAINTENANCE }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
  labels:
    name: box-server
    app: botium-box
    tier: frontend
    mode: maintenance
spec:
  selector:
    matchLabels:
      app: maintenance
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: maintenance
        tier: backend
    spec:
      containers:
        - name: maintenance
          image: adrianrudnik/maintenance-server:latest
          ports:
            - name: mt-80
              containerPort: 80
{{- end }}
