{{- if .Values.ENABLE_BACKUP_PRISMA_CONFIG }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: prisma-config-backup-scheduler
spec:
  schedule: "{{ .Values.BACKUP_SCHEDULE }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: prisma-config-backup-s3
            image: murliwatz/docker-s3-backup:1.6
            imagePullPolicy: Always
            command: ["/bin/sh"]
            args: ["dobackup.sh"]
            volumeMounts:
            - mountPath: "/data"
              name: botium-box-prisma-config-storage
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: S3_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: S3_SECRET_ACCESS_KEY
            - name: BACKUP_NAME
              value: "prisma-config"
            - name: SUB_PATH
              value: "/"
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.S3_REGION }}"
            - name: S3_BUCKET_URL
              value: "s3://{{ .Values.S3_BUCKET }}/prisma-config/"
            - name: S3_ENDPOINT
              value: "{{ .Values.S3_ENDPOINT }}"
            - name: S3_REGION
              value: "{{ .Values.S3_REGION }}"
          restartPolicy: OnFailure
          volumes:
            - name: botium-box-prisma-config-storage
              persistentVolumeClaim:
                claimName: botium-box-prisma-config-storage
                readOnly: true
{{- end }}
