{{- if .Values.ENABLE_PROVISIONER }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: box-provisioner
  labels:
    name: box-provisioner
    app: botium-box-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: box-provisioner
      app: botium-box-provisioner
  template:
    metadata:
      labels:
        name: box-provisioner
        app: botium-box-provisioner
    spec:
      containers:
        - name: box-provisioner
          {{- if eq .Values.CONTAINER_REGISTRY "" }}
          mage: botium/botium-box-server:{{ .Values.BOTIUM_BOX_VERSION }}
          {{- else }}
          image: {{ .Values.CONTAINER_REGISTRY }}/botium/botium-box-server:{{ .Values.BOTIUM_BOX_VERSION }}
          {{- end }}
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c", "npm run start:dist:provisioner"]
          volumeMounts:
          - mountPath: "/app/prisma-config/"
            name: botium-box-prisma-config-storage
          env:
            - name: DEBUG
              value: botium*
            - name: BOTIUMBOX_QUEUE_SETTINGS
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: BOTIUMBOX_QUEUE_SETTINGS
            - name: BOTIUMBOX_QUEUE_REDISURL
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: BOTIUMBOX_QUEUE_REDISURL
            - name: BOTIUMBOX_QUEUE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_QUEUE_PREFIX                             
            - name: LICENSE_KEY
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: LICENSE_KEY
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: DATABASE_URL
            - name: BOTIUMBOX_LOG_JSON
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: BOTIUMBOX_LOG_JSON
            - name: BOTIUMBOX_SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: botium-box-secrets
                  key: BOTIUMBOX_SENTRY_DSN
            - name: PRISMA_CONFIG_FILE
              valueFrom:
                configMapKeyRef:
                  name: botium-box-configmap
                  key: PRISMA_CONFIG_FILE
      volumes:
        - name: botium-box-prisma-config-storage
          persistentVolumeClaim:
            claimName: botium-box-prisma-config-storage
{{- end }}
