apiVersion: v1
kind: Secret
metadata:
  name: botium-speech-processing-secrets
  labels:
    name: secrets
    app: botium-speech-processing
stringData:
  AUTH_APIKEYS: "{{ .Values.AUTH_APIKEYS }}"
  BOTIUM_SPEECH_GOOGLE_CLIENT_EMAIL: "{{ .Values.BOTIUM_SPEECH_GOOGLE_CLIENT_EMAIL }}"
data:
  BOTIUM_SPEECH_GOOGLE_PRIVATE_KEY: "{{ .Values.BOTIUM_SPEECH_GOOGLE_PRIVATE_KEY }}"
type: Opaque
