apiVersion: v1
kind: Secret
metadata:
  name: botium-speech-processing-secrets
  labels:
    name: secrets
    app: botium-speech-processing
stringData:
  AUTH_APIKEYS: "{{ .Values.AUTH_APIKEYS }}"
type: Opaque
