apiVersion: v1
kind: Secret
metadata:
  name: botium-speech-processing-secrets
  labels:
    name: secrets
    app: botium-speech-processing
stringData:
  BOTIUM_API_TOKENS: "{{ .Values.BOTIUM_API_TOKENS }}"
  BOTIUM_SPEECH_GOOGLE_CLIENT_EMAIL: "{{ .Values.BOTIUM_SPEECH_GOOGLE_CLIENT_EMAIL }}"
  BOTIUM_SPEECH_IBM_STT_APIKEY: "{{ .Values.BOTIUM_SPEECH_IBM_STT_APIKEY }}"
  BOTIUM_SPEECH_IBM_STT_SERVICEURL: "{{ .Values.BOTIUM_SPEECH_IBM_STT_SERVICEURL }}"
  BOTIUM_SPEECH_IBM_TTS_APIKEY: "{{ .Values.BOTIUM_SPEECH_IBM_TTS_APIKEY }}"
  BOTIUM_SPEECH_IBM_TTS_SERVICEURL: "{{ .Values.BOTIUM_SPEECH_IBM_TTS_SERVICEURL }}"
  BOTIUM_SPEECH_AZURE_SUBSCRIPTION_KEY: "{{ .Values.BOTIUM_SPEECH_AZURE_SUBSCRIPTION_KEY }}"
  BOTIUM_SPEECH_AZURE_REGION: "{{ .Values.BOTIUM_SPEECH_AZURE_REGION }}"
  BOTIUM_SPEECH_AWS_REGION: "{{ .Values.BOTIUM_SPEECH_AWS_REGION }}"
  BOTIUM_SPEECH_AWS_ACCESS_KEY_ID: "{{ .Values.BOTIUM_SPEECH_AWS_ACCESS_KEY_ID }}"
  BOTIUM_SPEECH_AWS_SECRET_ACCESS_KEY: "{{ .Values.BOTIUM_SPEECH_AWS_SECRET_ACCESS_KEY }}"
  BOTIUM_SPEECH_AWS_S3_BUCKET: "{{ .Values.BOTIUM_SPEECH_AWS_S3_BUCKET }}"
data:
  BOTIUM_SPEECH_GOOGLE_PRIVATE_KEY: "{{ .Values.BOTIUM_SPEECH_GOOGLE_PRIVATE_KEY }}"
type: Opaque
