apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botium-speech-processing-claim
  labels:
    name: botium-speech-processing-claim
    app: botium-speech-processing
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.BOTIUM_SPEECH_PROCESSING_STORAGE_CLASS}}
  resources:
    requests:
{{- if eq .Values.BOTIUM_SPEECH_PROVIDER_TTS "kaldi"}}
      # storage for frontend + stt + tts?
      storage: 10Gi
{{- else }}
      storage: 512Mi
{{- end }}
