apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botium-speech-processing-claim
  labels:
    name: botium-speech-processing-claim
    app: botium-speech-processing
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.BOTIUM_SPEECH_PROCESSING_STORAGE_CLASS}}
  resources:
    requests:
      storage: 5Gi
