apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    name: frontend
    app: botium-speech-processing
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: frontend
      app: botium-speech-processing
  template:
    metadata:
      labels:
        name: frontend
        app: botium-speech-processing
        tier: frontend
    spec:
      volumes:
        - name: botium-speech-processing-storage
          persistentVolumeClaim:
            claimName: botium-speech-processing-claim
      containers:
        - name: frontend
          image: botium/botium-speech-frontend:{{ .Values.BOTIUM_SPEECH_PROCESSING_VERSION }}
          ports:
            - name: frontend-56000
              containerPort: 56000
          volumeMounts:
            - mountPath: /app/resources
              name: botium-speech-processing-storage
          env:
            - name: BOTIUM_API_TOKENS
              valueFrom:
                secretKeyRef:
                  name: botium-speech-processing-secrets
                  key: BOTIUM_API_TOKENS
            - name: BOTIUM_SPEECH_PROVIDER_TTS
              valueFrom:
                configMapKeyRef:
                  name: botium-speech-processing-configmap
                  key: BOTIUM_SPEECH_PROVIDER_TTS
            - name: BOTIUM_SPEECH_PROVIDER_STT
              valueFrom:
                configMapKeyRef:
                  name: botium-speech-processing-configmap
                  key: BOTIUM_SPEECH_PROVIDER_STT
            - name: BOTIUM_SPEECH_GOOGLE_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: botium-speech-processing-secrets
                  key: BOTIUM_SPEECH_GOOGLE_CLIENT_EMAIL
            - name: BOTIUM_SPEECH_GOOGLE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: botium-speech-processing-secrets
                  key: BOTIUM_SPEECH_GOOGLE_PRIVATE_KEY
            - name: BOTIUM_SPEECH_IBM_STT_APIKEY
              valueFrom:
                secretKeyRef:
                  name: botium-speech-processing-secrets
                  key: BOTIUM_SPEECH_IBM_STT_APIKEY
            - name: BOTIUM_SPEECH_IBM_STT_SERVICEURL
              valueFrom:
                secretKeyRef:
                  name: botium-speech-processing-secrets
                  key: BOTIUM_SPEECH_IBM_STT_SERVICEURL
            - name: BOTIUM_SPEECH_IBM_TTS_APIKEY
              valueFrom:
                secretKeyRef:
                  name: botium-speech-processing-secrets
                  key: BOTIUM_SPEECH_IBM_TTS_APIKEY
            - name: BOTIUM_SPEECH_IBM_TTS_SERVICEURL
              valueFrom:
                secretKeyRef:
                  name: botium-speech-processing-secrets
                  key: BOTIUM_SPEECH_IBM_TTS_SERVICEURL
            - name: BOTIUM_SPEECH_AZURE_SUBSCRIPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: botium-speech-processing-secrets
                  key: BOTIUM_SPEECH_AZURE_SUBSCRIPTION_KEY
            - name: BOTIUM_SPEECH_AZURE_REGION
              valueFrom:
                secretKeyRef:
                  name: botium-speech-processing-secrets
                  key: BOTIUM_SPEECH_AZURE_REGION
            - name: BOTIUM_SPEECH_AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: botium-speech-processing-secrets
                  key: BOTIUM_SPEECH_AWS_REGION
            - name: BOTIUM_SPEECH_AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: botium-speech-processing-secrets
                  key: BOTIUM_SPEECH_AWS_ACCESS_KEY_ID
            - name: BOTIUM_SPEECH_AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: botium-speech-processing-secrets
                  key: BOTIUM_SPEECH_AWS_SECRET_ACCESS_KEY
            - name: BOTIUM_SPEECH_AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: botium-speech-processing-secrets
                  key: BOTIUM_SPEECH_AWS_S3_BUCKET                  
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 56000
      targetPort: 56000
  selector:
    name: frontend
    app: botium-speech-processing
