{{- if eq .Values.BOTIUM_SPEECH_PROVIDER_STT "kaldi"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt-de
  labels:
    name: stt-de
    app: botium-speech-processing
    tier: stt-de
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: stt-de
      app: botium-speech-processing
  template:
    metadata:
      labels:
        name: stt-de
        app: botium-speech-processing
        tier: stt-de
    spec:
      volumes:
        - name: botium-speech-processing-storage
          persistentVolumeClaim:
            claimName: botium-speech-processing-claim
      containers:
        - name: stt-de
          image: botium/botium-speech-kaldi-de:{{ .Values.BOTIUM_SPEECH_PROCESSING_VERSION }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - mountPath: /opt/logs
              name: botium-speech-processing-storage
---
apiVersion: v1
kind: Service
metadata:
  name: stt-de
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 56180
      targetPort: 56180
  selector:
    name: stt-de
    app: botium-speech-processing
{{- end }}
