{{- if eq .Values.BOTIUM_SPEECH_PROVIDER_TTS "marytts"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tts
  labels:
    name: tts
    app: botium-speech-processing
    tier: tts
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: tts
      app: botium-speech-processing
  template:
    metadata:
      labels:
        name: tts
        app: botium-speech-processing
        tier: tts
    spec:
      containers:
        - name: tts
          image: botium/botium-speech-marytts:{{ .Values.BOTIUM_SPEECH_PROCESSING_VERSION }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: tts
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 59125
      targetPort: 59125
  selector:
    name: tts
    app: botium-speech-processing

{{- end }}
