{{- if eq .Values.BOTIUM_SPEECH_PROVIDER_TTS "kaldi"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictate
  labels:
    name: dictate
    app: botium-speech-processing
    tier: dictate
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: dictate
      app: botium-speech-processing
  template:
    metadata:
      labels:
        name: dictate
        app: botium-speech-processing
        tier: dictate
    spec:
      containers:
        - name: dictate
          image: botium/botium-speech-dictate:{{ .Values.BOTIUM_SPEECH_PROCESSING_VERSION }}
          ports:
            - name: dictate-56100
              containerPort: 56100
---
apiVersion: v1
kind: Service
metadata:
  name: dictate
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 56100
  selector:
    name: dictate
    app: botium-speech-processing
{{- end }}
