apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: speech-processing-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    rancher.io/globalDNS.hostname: {{ .Values.SHORTNAME }}.botiumbox.com
spec:
  rules:
    - host: {{ .Values.SHORTNAME }}.botiumbox.com
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 56000
          - path: /tts
            backend:
              serviceName: tts
              servicePort: 59125
          - path: /stt_en
            backend:
              serviceName: stt_en
              servicePort: 80
          - path: /stt_de
            backend:
              serviceName: stt_de
              servicePort: 80
          - path: /dictate
            backend:
              serviceName: dictate
              servicePort: 56100

---
#apiVersion: cert-manager.io/v1alpha2
#kind: Issuer
#metadata:
#  name: {{ .Values.SHORTNAME }}-letsencrypt-prod
#spec:
#  acme:
#    server: https://acme-v02.api.letsencrypt.org/directory
#    email: florian.treml@botium.at
#    privateKeySecretRef:
#      name: {{ .Values.SHORTNAME }}-letsencrypt-prod
#    solvers:
#      - selector: {}
#        http01:
#          ingress:
#            class: nginx
---
#apiVersion: cert-manager.io/v1alpha2
#kind: Certificate
#metadata:
#  name: {{ .Values.SHORTNAME }}.botiumbox-com
#spec:
#  secretName: {{ .Values.SHORTNAME }}.botiumbox-com-tls
#  issuerRef:
#    name: {{ .Values.SHORTNAME }}-letsencrypt-prod
#  commonName: {{ .Values.SHORTNAME }}.botiumbox.com
#  dnsNames:
#    - {{ .Values.SHORTNAME }}.botiumbox.com
