apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: speech-processing-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.USE_RANCHER}}
    {{- if not .Values.FQDN ""}}
    rancher.io/globalDNS.hostname: {{ .Values.FQDN }}
    {{- end }}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 56000
          {{- if eq .Values.BOTIUM_SPEECH_PROVIDER_TTS "marytts"}}
          - path: /tts
            backend:
              serviceName: tts
              servicePort: 59125
          {{- end }}
          {{- if eq .Values.BOTIUM_SPEECH_PROVIDER_STT "kaldi"}}
          - path: /stt-en
            backend:
              serviceName: stt-en
              servicePort: 80
          - path: /stt-de
            backend:
              serviceName: stt-de
              servicePort: 80
          - path: /dictate
            backend:
              serviceName: dictate
              servicePort: 56100
    {{- if not .Values.FQDN ""}}
    host: { { .Values.FQDN } }
    { { - end } }
  {{- end }}
